### ISSUE TITLE
In chat user name

### ISSUE THREAD

**Issue by mxpio** [fetlife/fetlife-android#12]
When in the FetChat(soon to be FetLife???) main screen, it shows all the users names that i have chatted with, but currently when in a chat with a specific person, it does not show the name of the person you are chatting with, only what i assume to be some sort of back end unique identifier. 

KinkedCuffs

**Comment by kistitan** [comment]
Hi there,

Indeed it is a technical id, that is going to be replaces.
New version can be expected tomorrow.

Thanks for testing and your feedback

**Comment by Fbiss** [comment]
This looks resolved on my android

SirBis
Samsung Note 5

**Comment by kistitan** [comment]
With new version it should be indeed solved so I close the issue ;)
Thank you for your support
