### ISSUE TITLE
Hyperlinks are not clickable

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#13]
Hyperlinks are not clickable.

SirBis
Android - Samsung Note 5

**Comment by kistitan** [comment]
@Fbiss 

Which hyperlinks you mean?
On the logon screen or within the chat messages?

Chat message formatting is just under improvement.
This will include better layout, copy paste function and probably the hyperlink function too.

Thanks

**Comment by Fbiss** [comment]
@Kistitan 

Sorry I should have specified where. I was referring to inside the chat message itself. 

Sounds like you are addressing that :)

**Comment by kistitan** [comment]
Yep thank you very much.
We are on it :)

**Comment by kistitan** [comment]
Hi there,

This issue should be solved now. 
Please install the new version of the apk to see the changes.

Note: before installing the new version you have to uninstall (or clear all data for) the previous version.
This is just a temporary solution uninstall won't be needed after 1.0 release.

Have a nice day

**Comment by Fbiss** [comment]
Yep, works thanks
