### ISSUE TITLE
Profile pictures are not displayed

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#14]
Not sure if this is a bug, not implemented yet, or by design. But the app only shows a placeholder image instead of the users profile picture.

SirBis
Android - Samsung Note 5

**Comment by kistitan** [comment]
Hi

Yep, image loading is an upcoming feature. 
It will be implemented probably after the paging and new conversations start features.
We will keep you updated.

Thanks

**Comment by kistitan** [comment]
Feature implemented. Please download the latest version
