### ISSUE TITLE
Login Page and Application appear as two applications in recent apps - Android

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#16]
I noticed after logging in, both the login page and list of messages appear as two separate applications in my recent applications switcher. 

SirBis
Android - Samsung Note 5

**Comment by JohnBaku** [comment]
@Fbiss by any chance can you share a screenshot of what you see?

**Comment by Fbiss** [comment]
http://i.imgur.com/GXzDePy.png

**Comment by JohnBaku** [comment]
@Fbiss thanks!

**Comment by kistitan** [comment]
Hi there,

We did not face that issue. 
We have some pending changes that will be pushed to the repository soon, and might fix this issue.
We will let you know if it is available for download.
If you could restest after and let us know if it still happen it would be appreciated.

Thanks

**Comment by Fbiss** [comment]
@kistitan 

Sure will

**Comment by Fbiss** [comment]
@kistitan 

Just installed the newest version, and same result with showing multiple applications in the recent apps page.

SirBis
Samsung Note 5

**Comment by kistitan** [comment]
Thank You!
It doesn't happen on our test device, but we will figure it out anyway.
We are on it :)

**Comment by kistitan** [comment]
I managed to reproduce the issue.
It is not solved yet in the latest version, but will be solved in the next release.

Thank you for your patience

**Comment by kistitan** [comment]
Hi thete,
This issue should be solved in the latest version.
If you had any issues with installation, please check out this thread:
https://github.com/fetlife/fetlife-android/issues/31
Thank you
