### ISSUE TITLE
New message indicator not distinct enough

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#17]
It looks as the new mail indicator on the messages list page bolds the text of the summary text. This doesn't stand out much that there is a new message. Maybe have it change the background color on that row to a different color, and potentially the new messages since last view inside the conversation can be color with the same background.

SirBis
Samsung Note 5

**Comment by kistitan** [comment]
Hi again,

This is a very valuable feedback. Indeed the bold white text not very obvious indicator.
As an improvement our first idea was to add a new message icon, smilar to the website, but different row color is also a good idea, that we should consider.

Thanks for your feedback

**Comment by kistitan** [comment]
Hi there,

This issue should be solved now. The new message indication might be changed later as we keep improving the styling of the app, but it is very visible now, so I close this issue for now.

Note: before installing the new version you have to uninstall (or clear all data for) the previous version.
This is just a temporary solution uninstall won't be needed after 1.0 release.

Have a nice day

**Comment by Fbiss** [comment]
new message indicator is working, thanks
