### ISSUE TITLE
Reading a message with the app does not mark the mail read on the website and vice versa

### ISSUE THREAD

**Issue by Fbiss** [fetlife/fetlife-android#19]
When you read an new mail using the application, it does not mark the same message as read on the mail indicator or on the mail message itself on the fetlife website.

also, if you check the mail on the website it does not sync with the application to let it know that the mail has been read.

**Comment by kistitan** [comment]
Hi there,

Thanks very much for your feedback.
Indeed this one of the upcoming feature we are working on together with the paging and starting new conversation.

We will keep you updated about the upcoming updates.

**Comment by kistitan** [comment]
Hi there,

This issue should be solved now. 
Please install the new version of the apk to see the changes.

Note: before installing the new version you have to uninstall (or clear all data for) the previous version.
This is just a temporary solution uninstall won't be needed after 1.0 release.

Have a nice day

**Comment by Fbiss** [comment]
Yep, seems to work. Thanks
