### ISSUE TITLE
Messages don't show new lines.

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/fetlife-android#23]
If I write a message I can add new lines to the message OK.
However both sent and received messages display with new lines ignored.

For example a message that read...
Line 1.
Line 2.
Line 3.

Would display in the app as...
Line 1. Line 2. Line 3.

NB - the message displays OK on the web.

**Comment by kistitan** [comment]
Hi and thank you for your report.
This is going to be fixed in next version that is coming soon.

**Comment by kistitan** [comment]
Hi there,

This issues should be solved now.
Please install the new version of the apk to see the changes.
Note: before installing the new version you have to uninstall (or clear all data for) the previous version.
This is just a temporary solution uninstall won't be needed after 1.0 release.

Have a nice day
