### ISSUE TITLE
First time use - login, use, back returns to login screen

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/fetlife-android#24]
First time use.
Login
Use the app.
Press the back button to exit.

Expect to close but it returns to the login screen.
Second time use is fine. It is still logged in and back exits as you expect.

This is mostly an annoyance. But it could give someone the impression they logged out when they haven't which could result in a privacy issue. So I'd recommend fixing ASAP.

**Comment by kistitan** [comment]
Hmm... indeed good and important point.
This issue is connected to another open issue about having the app twice in the recent app list.

I will make sure it will be fixed in the next version.

Thanks

**Comment by kistitan** [comment]
Hi there,
Issue should be solved in the latest release.
If you had any problems during the installation please check this thread:
https://github.com/fetlife/fetlife-android/issues/31
Thanks

**Comment by FernandoMiguel** [comment]
v1.5.1 defaults to NOT save logins.
shouldnt it be the other way around for the kinky version of the app?
i guess the vanilla version is OK to ask again, but not the kinky.
