### ISSUE TITLE
Version tracking

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/fetlife-android#26]
At the moment there is no way to determine what version I'm running or what the latest version is. We could do with a simple manual method in the short term.

1) Can you add an about screen to check the current version.
2) Can the current version be added to the Readme?

**Comment by kistitan** [comment]
Sure, good point. 
We definitely going to add it.
We plan to have it when 1.0 version is released.

As current version is still missing some essential features (for example paging and starting new conversation) it is still a preliminary beta version. 
But anyway, I will make sure it is in our backlog.

**Comment by kistitan** [comment]
Hi there,

A new version is available.
From this version you will be able to see the version of the app, by opening the menu.

As of now it is visible under your user name.
In the future we might have a separate about view for this purpose.

Have a nice day
