### ISSUE TITLE
Rename App from "FetChat" to FetLife

### ISSUE THREAD

**Issue by JohnBaku** [fetlife/fetlife-android#3]
Since we are slowly going to be moving in the direction of our Android app being a full-featured all I think we should rename the app from FetChat to FetLife.

**Comment by kistitan** [comment]
Renamed app version is coming soon together with some bug fixes.

**Comment by Fbiss** [comment]
This looks resolved on Android

SirBis
Samsung Note 5

**Comment by kistitan** [comment]
This indeed should be solved now :)
Thanks for the support for both of you.
