### ISSUE TITLE
Null Mention Notifications 

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#33]
Opening an issue just for future reference as it'll likely be a future feature, although currently all mention notifications are given a null or empty route upon being clicked.

Until the app is given the ability to actually access Fetlife's core service, the notifications should temporarily open a link in the user's default web browser routing to the associated comment already provided in the API response.

**Comment by reneklacan** [comment]
We actually haven't realized that mention notifications are going to Android app too 😅

**Comment by reneklacan** [comment]
I am still having slow conversation with OneSignal about this, I will fix it as soon as I can.
