### ISSUE TITLE
Better Installation FAQ

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#35]
While first downloading the .apk onto a computer (or separate device) and then copying the file onto the Android device is possible, it is much easier to instruct users to simply navigate to the [fetlife-debug.apk](https://github.com/fetlife/fetlife-android/raw/master/FetLifeApp/fetlife-debug.apk) on the Android device, download it directly onto the device, and then either open it within their Downloads folder or allow the browser to automatically recommend opening it.

This saves a lot of effort on the end user's part, makes it easier for tech savvies to assist others with installing the application, and also requires no other software / other devices for installation.

**Comment by Daddy** [comment]
Another concern of installing via a computer is the risks of security and hacking for kinksters who are connecting their devices to another laptop. While many may have good intents, there are many ways of quickly extracting data from a device during the time the app is downloaded or installed.

Many events are also not appropriate for bringing laptops such as dungeons or some restaurants, whereas installing via the device's browser is both quick, easy, and can be completed in a matter of a few minutes. 👍

**Comment by AzScots** [comment]
Link to the app is busted -404

**Comment by thezerogod** [comment]
Current link is https://raw.githubusercontent.
com/fetlife/fetlife-android/master/FetLifeApp/v0_5_1/fetlife-debug.apk


mxter zero
zero@mxterzero.com

**Comment by kistitan** [comment]
Readme file updated.
We are going to use tags for older versions if needed.

Thanks
