### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#37]
While making directories (referencing commit 08ed03d75a3f4d99771c80bf839c0d989b2fcbcf) can be done and serves it's purposes, with future version updates, this can add substantially to the size of the repository.

I would recommend instead, reverting this change (going back to only one .apk) within the actual repository, and creating a version tag with any full version changes and upload the compiled .apk there to not only allow for better organizing, but make it easier for both general users and developers to see what has changed with each version similar to what would be displayed on the Google Play store.

This allows for a better overall experience for everyone and also would make it easier for installing the application for non-tech savvy individuals.

**Comment by kistitan** [comment]
Hi Daddy
Good comment. We definitely don't want all the versions in the repository.
I like your proposal so most probably we will use it, however we should think of what is the most straightforward access for everyone including those who are not very familiar with git and repositories.

We will discuss the best opportunities for distribution.
Anyway thanks again for the valuable suggestion, I keep this thread open until we set up a more convenient solution.

**Comment by Daddy** [comment]
@kistitan Thank you for the response and look forward to updates as well. One of the biggest positives to the idea of versioning is the user-friendliness of it for everyone who is not very familiar with GitHub / git as you mentioned. Instead of having to navigate through the repository and locate the .apk manually (which can be stressful for anybody not familiar with Android SDK projects), they can simply know to visit versions and download a stable version of the application.

By using versioning this would allow for @JohnBaku to include a section with each weekly update on Fetlife to the direct link of any new versions of the app (and any notable updates), or simply link to the current version if there hasn't been any version releases.

**Comment by kistitan** [comment]
Readme file updated.
Currently we have one stable version, if will need again older version we are going to use it from a  special commit as suggested.

Thanks!
