### ISSUE TITLE
Download moved?

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/fetlife-android#38]
I'm going to...
https://github.com/fetlife/fetlife-android

Then following the link
5. Copy the **fetlife-debug.apk** file to your device

This links to URL...
https://github.com/fetlife/fetlife-android/raw/master/FetLifeApp/fetlife-debug.apk

Which is now showing a 404 error. :-(
_(I assume this is because there is now a current and last version.)_

**Comment by Daddy** [comment]
In the commit 08ed03d pushed today, the location of the .apk was moved.

The new location can be found [here](https://github.com/fetlife/fetlife-android/blob/master/FetLifeApp/v0_5_1/fetlife-debug.apk), although that might also be changing following what happens with #37. This of course will not always route to the "current" version and v0_5_1 will have to be replaced with whatever the live version at the time.

**Comment by kistitan** [comment]
Correct, thank you Daddy.
With new versions we are going to go with your proposal probably, so location is going to change again, once more at least :)

Next version with profile images is almost there :)
