### ISSUE TITLE
Add/Reject/View Friend Requests

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#55]
With the addition of a friends list, there should be a way to easily add a user via their username, which would send a notification to the user both on the main service as well as the application.

Clicking on the notification should open up a "Friend Requests" view which can be accessed via the friends list. There would be a list of all pending requests, than a ✔️ or a ✖️ to approve or reject the request(s).

**Goal**
This would allow for easily adding new individuals met at events or happenings and reduce the chore of having to open a browser window > search for their name > and send a request.

**Comment by kistitan** [comment]
Hi Daddy,

Good idea. I added on our feature list.
As of now without any exact plan yet.

**Comment by kistitan** [comment]
Approve, reject friend request functionality have been added into version 1.1.0.
Sending new friend request is postponed for later releases.

**Comment by Merseygeek** [comment]
Just installed 1.1.0, having login issues. I get a message ''server unreachable'' when trying to log in.
