### ISSUE TITLE
NFC for Messaging and Profiles

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#56]
To make the process of inter-connecting with individuals on Fetlife easier, the app should allow for NFC communication between clients. This should be enabled by default and trigger upon two devices having the Fetlife application open and "tap" against each other.

**Goal:**
Upon two devices tapping against each other with the Fetlife application open, it should automatically send a friend request to each other, with a dialog to confirm or deny the request. Alternatively, once profile views are included in the application, it can open up the user's profile to either browse or add as a friend if wanted.

**Comment by reneklacan** [comment]
adding a friend via NFC sounds pretty cool 👍

**Comment by kistitan** [comment]
Hi Daddym

Awesome idea. :)
Pretty cool.

We definitely should do this.
Unfortunately we have some prerequisites that we should implement first so it will take some time, but it is on our list!

**Comment by kistitan** [comment]
Feature implemented in version 1.2.0
