### ISSUE TITLE
Improve New Conversation Title

### ISSUE THREAD

**Issue by Daddy** [fetlife/fetlife-android#59]
With the latest changes, upon clicking the new conversation button it launches the friends list and then clicking on a user opens up an empty conversation window. In this selection screen, the title "Friends" is displayed.

At the same time, the new Friends list also has a title of "Friends" which can cause confusion. If a user leaves the app on this screen, there is no way to know whether or not they've left with the new conversation window open, or if they are on the regular Friends list and clicking a name will open the user's profile.

**Goal:**
Change the name of the new conversation view to "New Conversation" or "Select a Friend.", to separate the two views and make navigating easier.

**Comment by kistitan** [comment]
Very good point, Will be fixed in the next version.

**Comment by Daddy** [comment]
👍

**Comment by kistitan** [comment]
Fixed in version 0.8.5
