### ISSUE TITLE
Style menu screen

### ISSUE THREAD

**Issue by kistitan** [fetlife/fetlife-android#61]
Make it bit less messy before version 1.0

**Comment by Daddy** [comment]
Expanding upon this, it might be nice to add counter bubbles to the sidebar items. So, a count of how many unread messages/conversations a user has, and a count of how many friends they have.

Just an idea, let me know your thoughts.

**Comment by kistitan** [comment]
Good idea we should improve also the backend communication to get this.
It won't be part of next release, but definitely should be on our todo list.
I open a separate issue for that.

**Comment by kistitan** [comment]
Menu styling will be improved in version 1.0.
