### ISSUE TITLE
Implement Kinky Chat

### ISSUE THREAD

**Issue by smiller171** [fetlife/fetlife-android#68]
Should be able to use the chat function in the app, not just messages

**Comment by JohnBaku** [comment]
@smiller171 what do you mean by KinkyChat and chat function?

**Comment by smiller171** [comment]
fetlife.com has a live chat feature (think facebook messenger) It's not very good, but enabling it on mobile woulr be a welcome addition.

**Comment by JohnBaku** [comment]
@smiller171 that had to be retired 2-3 months ago unfortunately! :-p

**Comment by smiller171** [comment]
@JohnBaku I hadn't realized. I don't get on the desktop site much. A new implementation could be an extremely valuable addition to the community.

Would you guys be opposed to me writing one as a 3rd party? I could copy your code here for getting the user list, and would implement my own online status check.

**Comment by smiller171** [comment]
looks like I need to ask @kistitan about that.

**Comment by JohnBaku** [comment]
@smiller171 we're currently working on a solution.
