### ISSUE TITLE
Login issue with special characters in password (IllegalStateException)

### ISSUE THREAD

**Issue by digi256** [fetlife/fetlife-android#71]
Logging in with the Fetlife App fails, potentially due to unescaped special characters in the GET request to Fetlife's oAuth service.

In my case I have a '^' in my password.

Looking at https://help.marklogic.com/Knowledgebase/Article/View/251/0/using-url-encoding-to-handle-special-characters-in-a-document-uri it seems an appropriate way may be escaping both e-mail addresses (as technically " "@example.com is legit, but would cause issues), and passwords using something like URLEncoder.encode(badUri, "UTF-8");

(Also, knowing that passwords may appear in Android's logs (accessible by at least logcat) makes me a little uneasy)

`adb logcat` output:
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime: FATAL EXCEPTION: IntentService[FetLifeApiIntentService]
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime: Process: com.bitlove.fetlife, PID: 20068
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime: java.lang.IllegalStateException: not valid as a java.net.URI: https://fetlife.com/api/oauth/token?client_id=[64 char hex string]&client_secret=[64 char hex string]&redirect_uri=urn:ietf:wg:oauth:2.0:oob&grant_type=password&username=test@example.com&password=[password with a ^ in it]
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.HttpUrl.uri(HttpUrl.java:336)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:135)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:71)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.internal.http.RouteSelector.get(RouteSelector.java:76)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:321)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.Call.getResponse(Call.java:267)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.bitlove.fetlife.model.api.FetLifeService$1.intercept(FetLifeService.java:33)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.squareup.okhttp.Call.execute(Call.java:79)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:61)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.bitlove.fetlife.model.service.FetLifeApiIntentService.logonUser(FetLifeApiIntentService.java:253)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at com.bitlove.fetlife.model.service.FetLifeApiIntentService.onHandleIntent(FetLifeApiIntentService.java:126)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
> 06-09 00:01:34.463 20068 20478 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
> 06-09 00:01:34.469  1884 13320 W ActivityManager:   Force finishing activity com.bitlove.fetlife/.view.LoginActivity

**Comment by kistitan** [comment]
Hi digi265,

Thanks for reporting. I have just noticed this issue and will fix soon.

About your concerns that password visible on log files.

I totally understand your point, however before trying answering it, let me state for other users that:
on supported Android version logs like that are visible only if you have a rooted phone or if you use android debug bridge for example. 

So as long as you do not root your phone and you do not give it to anybody who you do not trust you are in safe.

In rooted phone in general there is no safe application. The only thing that you can do is to raise the bar that needed to go across to hack the app and to trust users who root their phone that they can keep it secure.

The way how you usually mitigate the risk of rooted phone is either you do not let the app running on a rooted phone (you also can not it make 100% sure) or you hide the information how the app works and you obfuscate the source code. 

As we decided to open source the app we have no more option to hide the implementation. 
So all what we can do is to trust and try to educate users with rooted phone they knew about the risk when they did it.

We have however still plans to improve the security also on rooted phones, like in this particular case, in not trustable environment, but 100% security cannot be reached in these situations.

**Comment by kistitan** [comment]
Issue has been fixed.
It occurred also with new messages with special character.

Fix will be available in version 1.0 (next version)

Thank you for your patience
