### ISSUE TITLE
labels for unlabled buttons.

### ISSUE THREAD

**Issue by stickbear2015** [fetlife/fetlife-android#81]
When using talkback on android their are unlabeled buttons next to individual conversations in the conversations list, and in the friends list as  well, and probably in other parts of the app I have yet to explore.
Labeling these buttons would go a long way to adding that one extra level of accessibility to an already awesomely accessible app right out of the box.

**Comment by kistitan** [comment]
Hi @stickbear2015 

Thank you very much for reporting this.
Definitely! We will add the labels to have a better accessibility cover.
Unfortunately it won't be part of the 1.0 release that we are going to upload today with some urget bug fixes, but I will make sure it will be part of the next release.

Thanks again!

**Comment by kistitan** [comment]
Fixed in v1.0.2
