### ISSUE TITLE
Name of .apk

### ISSUE THREAD

**Issue by JohnBaku** [fetlife/fetlife-android#82]
Here is a screenshot:

![release_fetlife_android_app_v1_0_0_ _fetlife_fetlife-android](https://cloud.githubusercontent.com/assets/22100/16093170/b21c834e-32ef-11e6-9127-0fc58d06e3be.png)

Do we want to call the file just `fetlife.apk` or is it standard to include the version number in the filename?

cc/ @kistitan

**Comment by reneklacan** [comment]
👍  I am not sure about standards but I feel using `FetLife-1.2.3.apk` would be very nice

**Comment by kistitan** [comment]
Fixed with latest release :  v1.0.2

**Comment by JohnBaku** [comment]
Thanks @kistitan
