### ISSUE TITLE
Have the app alert users if they are not on the latest version

### ISSUE THREAD

**Issue by kdom13** [fetlife/fetlife-android#86]
I don't mind coming to github to download the latest version, nor do I mind manually uninstalling the older version, however I don't check github all that frequently and you guys are updating pretty rapidly!

**Comment by Daddy** [comment]
This would be possible by using one of Github's APIs to check the list of available versions, pull the newest one, and then alert the user via the app. However, these kind of alerts can be bothersome.

A better idea (if this is considered) would be to display that there is a new version available in the About area of the app, either around or below the current version. In the case the app is transitioned to the actual Google Play Store, this obviously won't be a concern as well.

**Comment by kdom13** [comment]
I don't think a one-time (non-recurring) alert would be bothersome at all, ESPECIALLY if it included a clickable link that would take you directly to the APK download =)

**Comment by reneklacan** [comment]
this would be great feature 👍

**Comment by kistitan** [comment]
Makes sense I am working on it

**Comment by Redroxy** [comment]
I still can't get 1.1 to install. Do I need uninstall former version first?  Have tried several things, but continually get 'app not installed'  msg.

**Comment by kdom13** [comment]
Wooo, I just got a notification while on 1.1.0 to update to 1.1.2 ... so I did! The notification didn't take anywhere (like to the download page), but still, great job =)

**Comment by kistitan** [comment]
@Redroxy 
Hey there, I am sorry I missed your comment.
Any success since than?
You should indeed uninstall any version before 1.0.0 to get the latest version.
After 1.0.0 no more uninstall is needed.

**Comment by kistitan** [comment]
@kdom13 
Yes, indeed we are working on improving with the notifications.
The one you got were only a temporary solution.

New notifications will be handed by the app and clicking on them will take you to the newest version.
Give us a bit more time to finish with the feature.

**Comment by Redroxy** [comment]
@kristitan. Got it. First uninstall worked this time. Thanks

**Comment by kistitan** [comment]
Notifications is sent out at each release now.
There is a general issue for improving the notifications (display only if version is lower, not loose the notifications), so I close this issue now.

**Comment by FernandoMiguel** [comment]
Can we do this with some granular care? 
Sending many notifications to users (per update) will fatigue them. 
Maybe just one notification per time app is open?

**Comment by kdom13** [comment]
@FernandoMiguel My actual intent with this request was actually a screen when you opened the app, not a notification, so that's what it would have been in my mind, but this works.

@kistitan Also, when trying to click the notification, it doesn't actually go anywhere, it just clears it.
