### ISSUE TITLE
Implement some sort of "sending" icon so that we know the app is communicating

### ISSUE THREAD

**Issue by kdom13** [fetlife/fetlife-android#89]
Currently, the app doesn't seem to have a way to tell us it is sending a message.  If it takes longer than usual, I'll just click the button again, because I didn't realize it was going.  Sometimes I'll try a few times, and then wind up with the message sent a few times.  It would be great to have some sort of "hourglass" that signifies the app is trying to communicate and send messages but hasn't actually sent yet.

**Comment by kistitan** [comment]
Hi @kdom13 ,

This is an interesting issue.
If you press the send button, messages are automatically saved into the database. No network connection you should wait for. It should be an almost instant operation.
So we cannot initiate a hour glass for that :)

Network operation gets initiated in the background so you do not need to wait for. 

Initially after pressing the send button you should see right away you message in the list as a greyed out messages and as soon as it is scynchronized with the server it turns automatically white like all the others.
If you see delay between pressing the button and seeing your message in grey in the list it means writing into the local db takes long, that in theory can happen only if for some reason your phone has limited resources.

**Comment by kdom13** [comment]
It's only happened to me once so far, and (based on date/time) this was right after I updated to 1.0.2.  Every other message I've sent I've noticed the gray/white transition.  So, I'm not quire sure what happened.

**Comment by kistitan** [comment]
Hi @kdom13,

It is still in important information.
Let me close this issue now and feel free to reopen if it happened again.

Thank you
