### ISSUE TITLE
The password is incorrect

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/fetlife-android#90]
I installed the latest version and tried to login but am getting an error message "The password is incorrect". I'm using LastPass to save the username / password and have tested it against the website without issue.

NB - The previous Fetlife app has stopped working for multiple people today. I suspect that something on the Fetlife backend has changed breaking both apps.

Running the latest version. According to the filename it is 1.0.2. (I can't check the in-app version without logging in.)
Nexus 6 with latest updates.

**Comment by restrainedimages** [comment]
I've reverted to the previous version which had previously worked - same results.
So this suggests a server side issue.

**Comment by reneklacan** [comment]
@restrainedimages I can confirm it's issue on our side. We've been doing some authentication changes and we broke API authentication.

We are really sorry for that.

Fix is currently being deployed.

**Comment by reneklacan** [comment]
Problem should be solved, I will close this issue now... Feel free to reopen it if you are still experiencing issues

**Comment by restrainedimages** [comment]
New app is working now.

The old one if still broke though. Suggest fixing that too so as to not alienate people while the functionality gap is closed. (I use both. Because the new is better at what it does. But there are things it doesn't do yet.)

J
