### ISSUE TITLE
v1.1.0 - Cannot Install over previous version

### ISSUE THREAD

**Issue by justrob1980** [fetlife/fetlife-android#93]
I downloaded the 1.1.0 apk and I could not install it over a previous version, believe it was 0.8. Kept getting "Install failed" when trying to install. I had to uninstall old version and install 1.1.0 fresh. 

Samsung SM-N920V
Android 6.0.1

**Comment by kistitan** [comment]
Thanks for the report.

From 1.0.0 all versions are signed with the official FetLife signing key that is different compared to the key used before.

From 1.0.0 you won't need to uninstall the previous version any more.
