### ISSUE TITLE
Server unreachable when logging in

### ISSUE THREAD

**Issue by Merseygeek** [fetlife/fetlife-android#95]
Just installed 1.1.0, having login issues. I get a message ''server unreachable'' when trying to log in

**Comment by Daddy** [comment]
Experiencing the same issue. When I was already logged in, everything would not load including conversations, friend requests, and so forth.

Upon logging out, attempting to login results in the same error.

**Comment by Daddy** [comment]
This appears to have been a server-sided issue and is now resolved. Unless @Merseygeek is still having issues, I think this can safely be closed.

**Comment by Merseygeek** [comment]
I will just check

**Comment by Merseygeek** [comment]
Sorted. Thanks guys and gals.

**Comment by kistitan** [comment]
Yes it should be solved now.
Thank you guys.
