### ISSUE TITLE
Need help for Naming a new feature 

### ISSUE THREAD

**Issue by kistitan** [fetlife/fetlife-android#98]
Hi guys,

I will need help with naming the following new feature:

If two Android App user meets at the party they do not need to write down their user name anymore to remember each other.
One of them should open the app select one menu item with name (this is the first question) like introduce/send my profile/ poke/ whatever, 
than tap her/his phone to the other's and her/his profile information is transferred.

After this the other user can see the transferred user profile on her/his friend request list. It is technically not a friend request yet,
as the nfc communication is one way only, so the other user could not start a friend request only send her/his profile information as kind of a friend request request.
So the friend request screen will be splitted into two sections: friend requests and (second naming question) friend suggestions/pokes/whatever.

If the user swipe this suggestion to the right a new friend request is going to be started so the original user who sent her^his profile can accept it.
Or of course with swipe left the user can reject the friend request request.

Any ideas?

**Comment by malachid** [comment]
On the old app, we implemented this as simply share. You could share any page you were on, including a profile. Share could be via email, hockey (throw it across the room), QR, or whatever you had installed.  So I'd recommend "Share Profile".

**Comment by thezerogod** [comment]
If you wanted to be cute about this you could call it "bind" or something...

**Comment by FernandoMiguel** [comment]
NFC has very little user market share. 
The default work should be done with qrcode. 
After that is been working, then you might implement NFC.

**Comment by GojuSuzi** [comment]
"Introduce" works fine, fairly self explanatory as a named item. If you're trying to fun it up, maybe something like "present" or "stimulate" or "tempt"?

**Comment by Daddy** [comment]
@GojuSuzi Introduce has a nice touch to it, I like that a bit. It's simple, clean, and is exactly what the feature does.. the only downside is there's not a kinky twist to it (but not necessary).

**Comment by Daddy** [comment]
Another idea could be "Touching Tips". :grin:

**Comment by kistitan** [comment]
@FernandoMiguel
Fortunatelly it is not true anymore. Close to 85% of the new Android devices supports HCE for example that requires NFC. 
And this stats is based on device type doesn't fully count market share.

For example NFC is a standard feature of Samsung devices since 2011 and Samsung has more than 63% of market share among Android devices. And it's only Samsung.

On the other hand QR code is an awesome idea!
Especially because we could use the feature also cross platform.

NFC feature is already implemented, but I definitely will add the QR code solution to our upcoming feature set.
Thanks for the hint!

**Comment by kistitan** [comment]
Thank you all for the ideas.
I like them all, especially the Touching Tips ;)
However I think @malachid has a very good point, sharing feature will be general within the all app so it would make sense to go with a standard name.

So next version the menu item will be probably "Share my profile". As of now only with NFC, later on via QR code and simple links.

Thanks again
